/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import DAO.LiberFactoryDao;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.accessibility.AccessibleContext;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.RowFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import static javax.swing.text.StyleConstants.Size;
import javax.xml.crypto.dsig.spec.ExcC14NParameterSpec;
import model.EseSueno;
import model.Product;
import model.TheModel;

/**
 *
 * @author royon
 */
public final class LiberFactory extends javax.swing.JFrame {
 String path2 = null;
    

    /**
     * Creates new form LiberFactory
     * @throws java.sql.SQLException
     */
    public LiberFactory() throws SQLException {
        initComponents();
        populateJTable();
       
        
    }
  
    private void sort()
{                                            
    TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(((TheModel) jTable2.getModel())); 
    sorter.setRowFilter(RowFilter.regexFilter(sortTxt.getText()));

    jTable2.setRowSorter(sorter);
}   
   

  public void Testing()
  {
    JPasswordField pwd = new JPasswordField(5);
    int action = JOptionPane.showConfirmDialog(null, pwd,"Enter Password for confirmation",JOptionPane.OK_CANCEL_OPTION);
    if(action < 0){JOptionPane.showMessageDialog(null,"Cancel, X or escape key selected");}
    else if( ! pwd.getPassword().equals("24155")){
        
          JOptionPane.showMessageDialog(this,"Password Incorrect");
      }
  
  
  }
  
    String imgPatth=null;
    
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        productidTxt = new javax.swing.JTextField();
        quantityTxt = new javax.swing.JTextField();
        priceTxt = new javax.swing.JTextField();
        imageliber = new javax.swing.JLabel();
        imaged = new javax.swing.JButton();
        registerProduct = new javax.swing.JButton();
        photoname = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        refreshBtton = new javax.swing.JButton();
        searchTxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        sumTxt = new javax.swing.JTextField();
        totalBudget = new javax.swing.JButton();
        sumQTxt = new javax.swing.JTextField();
        quantitySum = new javax.swing.JButton();
        totalTxt = new javax.swing.JTextField();
        totalBtton = new javax.swing.JButton();
        updateBttn = new javax.swing.JButton();
        deleteBttn = new javax.swing.JButton();
        sizeJlist = new javax.swing.JTextField();
        sortTxt = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        totalBySizeTxt = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jTabbedPane1.setBackground(new java.awt.Color(0, 0, 0));
        jTabbedPane1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jTabbedPane1ComponentShown(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Product ID");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Quantity");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Price per unit");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Size (S,M,L,XL or XXL)");

        productidTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productidTxtActionPerformed(evt);
            }
        });

        quantityTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityTxtActionPerformed(evt);
            }
        });

        priceTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceTxtActionPerformed(evt);
            }
        });

        imageliber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        imageliber.setMaximumSize(new java.awt.Dimension(208, 212));
        imageliber.setMinimumSize(new java.awt.Dimension(208, 212));

        imaged.setText("Choose Image Product");
        imaged.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imagedActionPerformed(evt);
            }
        });

        registerProduct.setText("Register Product");
        registerProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerProductActionPerformed(evt);
            }
        });

        photoname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                photonameActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable2);

        refreshBtton.setText("Refresh");
        refreshBtton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBttonActionPerformed(evt);
            }
        });

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        sumTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumTxtActionPerformed(evt);
            }
        });

        totalBudget.setText("Money Spent");
        totalBudget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalBudgetActionPerformed(evt);
            }
        });

        quantitySum.setText("Total Products");
        quantitySum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantitySumActionPerformed(evt);
            }
        });

        totalTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                totalTxtMouseClicked(evt);
            }
        });
        totalTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalTxtActionPerformed(evt);
            }
        });

        totalBtton.setText("Total ");
        totalBtton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalBttonActionPerformed(evt);
            }
        });

        updateBttn.setText("Update");
        updateBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBttnActionPerformed(evt);
            }
        });

        deleteBttn.setText("Delete");
        deleteBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBttnActionPerformed(evt);
            }
        });

        jButton2.setText("Sort by size:");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\royon\\OneDrive\\Images\\WhatsApp Image 2022-09-01 at 3.55.36 PM.jpeg")); // NOI18N

        jButton3.setText("Logout");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Inventory");

        jButton4.setText("jButton4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(registerProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(updateBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(totalBtton)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel2))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(productidTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(quantityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(totalTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(priceTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(sizeJlist, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(77, 77, 77)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(imageliber, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(imaged))
                        .addGap(27, 27, 27)
                        .addComponent(photoname, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(473, Short.MAX_VALUE)
                        .addComponent(deleteBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 68, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(refreshBtton)
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(276, 276, 276)
                        .addComponent(jButton3)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sumTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(sumQTxt)
                            .addComponent(totalBySizeTxt, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(totalBudget, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(quantitySum, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(sortTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(38, 38, 38)
                                .addComponent(searchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(156, 156, 156))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(refreshBtton))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalBudget)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton1)
                                    .addComponent(searchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(sumQTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(quantitySum)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton2)
                                    .addComponent(sortTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalBySizeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(productidTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(quantityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(priceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(totalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(totalBtton))
                                .addGap(16, 16, 16)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(sizeJlist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(imageliber, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addGap(72, 72, 72)
                                        .addComponent(photoname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(imaged)))
                        .addGap(39, 39, 39)
                        .addComponent(registerProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(updateBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                        .addComponent(deleteBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1460, 960));

        jTabbedPane1.addTab("Liber Factory", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1490, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTabbedPane1ComponentShown

    }//GEN-LAST:event_jTabbedPane1ComponentShown

    private void photonameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_photonameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_photonameActionPerformed

   
    
    private void registerProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerProductActionPerformed
        // TODO add your handling code here:
        
        
        if(productidTxt.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null,"Product is mandatory","Mandatory Field", JOptionPane.WARNING_MESSAGE);
        }
        else if(quantityTxt.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null,"Quantity is mandatory","Mandatory Field", JOptionPane.WARNING_MESSAGE);
        }else if(priceTxt.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null,"Price is mandatory","Mandatory Field", JOptionPane.WARNING_MESSAGE);
        }else if(totalTxt.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null,"Total is mandatory, please press on the total button","Mandatory Field", JOptionPane.WARNING_MESSAGE);
        }
        
        else if( sizeJlist.getText().equals("S") 
                ||sizeJlist.getText().equals("M")
                ||sizeJlist.getText().equals("L")
                ||sizeJlist.getText().equals("XL")
                ||sizeJlist.getText().equals("XXl")){


       
            String productid = productidTxt.getText();
        int price = Integer.parseInt(priceTxt.getText());
        int quantity = Integer.parseInt(quantityTxt.getText());
        int price_total= Integer.parseInt(totalTxt.getText());
        
        
        String size = sizeJlist.getText();
            // 2. Check if student Id is 5 characters
            if(productidTxt.getText().trim().length()<4){
                try {
                    
                    
                    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ese_sueno_db_management","root","");
                    String sql = "insert into liberfactoryinventory (product_id,size_,price,quantity,price_total,image) values(?,?,?,?,?,?)";
                    PreparedStatement pst = con.prepareStatement(sql);
                    
                    pst.setString(1, productid);
                    pst.setString(2,size);
                    pst.setInt(3, price);
                    pst.setInt(4, quantity);
                    pst.setInt(5, price_total);
                    InputStream is= new FileInputStream(new File(path2));
                    pst.setBlob(6,is);
                    
                    pst.execute();
                    productidTxt.setText("");
                    priceTxt.setText("");
                    photoname.setText("");
                    quantityTxt.setText("");
                    sizeJlist.setText(" ");
                    totalTxt.setText("");
                    imageliber.setIcon(null);
                    JOptionPane.showMessageDialog(null, "Product Saved");
                    
                } catch (SQLException ex) {
                    ex.printStackTrace();
                } catch (FileNotFoundException ex) {
                    ex.printStackTrace();
                }
               
            }else{
                JOptionPane.showMessageDialog(null, "Product ID should have at mpst 3 characters","Character Range", JOptionPane.WARNING_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Put a correct Size","Mandatory", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_registerProductActionPerformed

    private void imagedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imagedActionPerformed
        // TODO add your handling code here:
        JFileChooser fchoser=new JFileChooser();
        fchoser.showOpenDialog(null);
        FileNameExtensionFilter filter = new FileNameExtensionFilter("* .Images", "jpg","gif","png");
        File f=fchoser.getSelectedFile();
        String path = f.getAbsolutePath();
        photoname.setText(path);
        try {
            BufferedImage bi = ImageIO.read(new File(path));
            Image img = bi.getScaledInstance(134, 172,Image.SCALE_SMOOTH);
            ImageIcon icon = new ImageIcon(img);
            imageliber.setIcon(icon);
            
            path2 = path;
        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }//GEN-LAST:event_imagedActionPerformed

    private void priceTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceTxtActionPerformed

    private void quantityTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityTxtActionPerformed

    private void productidTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productidTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productidTxtActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
    
    }

     public void populateJTable() throws SQLException{
        LiberFactoryDao lf = new LiberFactoryDao();
        ArrayList<Product> list = lf.BindTable();
        String[] columnName = {"Product ID", "Qte", "Price", "Size", "Image"};
        Object[][] rows = new Object[list.size()][5];
        for(int i = 0; i< list.size();i++){
            rows[i][0]= list.get(i).getProduct_id();
            rows[i][1]= list.get(i).getQuantity();
            rows[i][2]= list.get(i).getPrice();
            rows[i][3]= list.get(i).getSize();
                    if(list.get(i).getImage() !=null){
                    ImageIcon image = new ImageIcon(new ImageIcon(list.get(i).getImage()).getImage().getScaledInstance(150,120, Image.SCALE_SMOOTH));
            rows[i][4]= image;
        }
                    else{
                        rows[i][4]=null;
                    }
        }
        TheModel model= new TheModel(rows, columnName);
        jTable2.setModel(model);
        jTable2.setRowHeight(120);
        jTable2.getColumnModel().getColumn(3).setPreferredWidth(150);
        
    }//GEN-LAST:event_jTable2MouseClicked

    private void refreshBttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBttonActionPerformed
     try {
         // TODO add your handling code here:
         populateJTable();
     } catch (SQLException ex) {
         Logger.getLogger(LiberFactory.class.getName()).log(Level.SEVERE, null, ex);
     }
    }//GEN-LAST:event_refreshBttonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    
      String productid = searchTxt.getText();
        
        
        if(searchTxt.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null,"Product is mandatory","Mandatory Field", JOptionPane.WARNING_MESSAGE);
        }
        
        

        else{
            // 2. Check if product Id is 5 characters
            if(searchTxt.getText().trim().length()>2){
                try {
                    
                    
                    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ese_sueno_db_management","root","");
            String sql = "select * from liberfactoryinventory where product_id=?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1,productid);
            ResultSet result = pst.executeQuery();
            Product p = new Product();
            boolean flag = false;
            while(result.next()){
                
                p.setSize(result.getString("size_"));
                p.setPrice(result.getInt("price"));
                p.setProduct_id(result.getString("product_id"));
                p.setQuantity(result.getInt("quantity"));
                p.setPrice_total(result.getInt("price_total"));
                byte[] img = result.getBytes("image");
              
                ImageIcon image = new ImageIcon(img);
                Image im = image.getImage();
                Image myImg = im.getScaledInstance(imageliber.getWidth(), imageliber.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon newImage= new ImageIcon(myImg);
                
                imageliber.setIcon(newImage);
                productidTxt.setText(p.getProduct_id());
                sizeJlist.setText(p.getSize());
                priceTxt.setText(String.valueOf(p.getPrice()));
                quantityTxt.setText(String.valueOf(p.getQuantity()));
                totalTxt.setText(String.valueOf(p.getPrice_total()));
                flag=true;
               
                
            }
            
            con.close();
            if(flag){
                System.out.println("Product ID : "+p.getProduct_id());
                
            }
        }catch(Exception ex){
            ex.printStackTrace();
        }
}
}
                    
                
                   
                
               
               
           


        
     
    }//GEN-LAST:event_jButton1ActionPerformed

    private void sumTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sumTxtActionPerformed

    private void totalBudgetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalBudgetActionPerformed
        // TODO add your handling code here:
    try {
                    
                    
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ese_sueno_db_management","root","");
    String sql = "Select sum(price_total) from liberfactoryinventory";
    PreparedStatement pst = con.prepareStatement(sql);
    ResultSet rs=pst.executeQuery();
    if(rs.next()){
       String sum=rs.getString("sum(price_total)")+" FCFA";
       sumTxt.setText(sum);
    }
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
    }
    }//GEN-LAST:event_totalBudgetActionPerformed

    private void quantitySumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantitySumActionPerformed
        // TODO add your handling code here:
        try {
                    
                    
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ese_sueno_db_management","root","");
    String sql = "Select sum(quantity) from liberfactoryinventory";
    PreparedStatement pst = con.prepareStatement(sql);
    ResultSet rs=pst.executeQuery();
    if(rs.next()){
       String sum=rs.getString("sum(quantity)");
       sumQTxt.setText(sum);
    }
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
    }
    }//GEN-LAST:event_quantitySumActionPerformed

    private void totalTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalTxtActionPerformed

        // TODO add your handling code here:
        
    }//GEN-LAST:event_totalTxtActionPerformed

    private void totalTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_totalTxtMouseClicked

        // TODO add your handling code here:
        int price = Integer.parseInt(priceTxt.getText());
        int quantity = Integer.parseInt(quantityTxt.getText());
        int price_total= price*quantity;
        
    }//GEN-LAST:event_totalTxtMouseClicked

    private void totalBttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalBttonActionPerformed
        // TODO add your handling code here:
        int price = Integer.parseInt(priceTxt.getText());
        int quantity = Integer.parseInt(quantityTxt.getText());
        int price_total= price*quantity;
        totalTxt.setText(String.valueOf(price_total));
    }//GEN-LAST:event_totalBttonActionPerformed

    private void updateBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBttnActionPerformed
        // TODO add your handling code here:
        if(productidTxt.getText().trim().isEmpty() 
          || priceTxt.getText().trim().isEmpty()
          || sizeJlist.getText().trim().isEmpty()
          || priceTxt.getText().trim().isEmpty()
          || totalTxt.getText().trim().isEmpty()
          
               )
       {
           JOptionPane.showMessageDialog(this, "All Fields are required");
       }else{
         String productid = productidTxt.getText();
        int price = Integer.parseInt(priceTxt.getText());
        int quantity = Integer.parseInt(quantityTxt.getText());
        int price_total= Integer.parseInt(totalTxt.getText());
        String size = (String) sizeJlist.getText();
        
        
        
            
            if(productidTxt.getText().trim().length()>2){
                try {
                    
                    
                    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ese_sueno_db_management","root","");
                    String sql = "update liberfactoryinventory set size_=?,price=?,quantity=?,price_total=? where product_id=?";
                    PreparedStatement pst = con.prepareStatement(sql);
                    
                    pst.setString(5, productid);
                    pst.setString(1,size);
                    pst.setInt(2, price);
                    pst.setInt(3, quantity);
                    pst.setInt(4, price_total);
                    
                    
                    pst.execute();
                    productidTxt.setText("");
                    priceTxt.setText("");
                    photoname.setText("");
                    quantityTxt.setText("");
                    sizeJlist.setText(" ");
                    totalTxt.setText("");
                    imageliber.setIcon(null);
                    JOptionPane.showMessageDialog(null, "Product Updated");
                    
                } catch (SQLException ex) {
                    ex.printStackTrace();}
               
               
            } else{
                JOptionPane.showMessageDialog(null, "Product ID should have at most 4 characters","Character Range", JOptionPane.WARNING_MESSAGE);
            }
        
        }
    }//GEN-LAST:event_updateBttnActionPerformed

    private void deleteBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBttnActionPerformed
        // TODO add your handling code here:
        if(productidTxt.getText().trim().isEmpty() 
          || sizeJlist.getText().trim().isEmpty()
          || priceTxt.getText().trim().isEmpty()
          || quantityTxt.getText().trim().isEmpty()
          || totalTxt.getText().trim().isEmpty())
      
       {
           JOptionPane.showMessageDialog(this, "all Fields are required");
       }else{
           
            String productid = productidTxt.getText();
        int price = Integer.parseInt(priceTxt.getText());
        int quantity = Integer.parseInt(quantityTxt.getText());
        int price_total= Integer.parseInt(totalTxt.getText());
        String size = (String) sizeJlist.getText();
        JPasswordField pwd = new JPasswordField(5);
    int action = JOptionPane.showConfirmDialog(null, pwd,"Enter Password for confirmation",JOptionPane.OK_CANCEL_OPTION);
    if(action < 0){JOptionPane.showMessageDialog(null,"Cancel, X or escape key selected");}
    else if(!pwd.getText().equals("24155")){
        
          JOptionPane.showMessageDialog(null,"Password Incorrect");
      }else{
           try{
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ese_sueno_db_management","root","");
            String sql = "delete from liberfactoryinventory where product_id=?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, productid);
            int rowAffected= pst.executeUpdate();
            con.close();
            
           if(rowAffected>0){
               JOptionPane.showMessageDialog(this, "Product deleted");
                    productidTxt.setText("");
                    priceTxt.setText("");
                    photoname.setText("");
                    quantityTxt.setText("");
                    sizeJlist.setText(" ");
                    totalTxt.setText("");
                    imageliber.setIcon(null);
           }else{
                JOptionPane.showMessageDialog(this, "Product not deleted");
           }
            
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }
        }
    }//GEN-LAST:event_deleteBttnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            sort();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        setVisible(false); //you can't see me!
        dispose(); //Destroy the JFrame object
            LogIn LogInFrame = new LogIn();
            LogInFrame.setVisible(true);
            LogInFrame.pack();
            LogInFrame.setLocation(null);  
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
try {
                    
                    
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ese_sueno_db_management","root","");
    String sql = "Select sum(price_total) from liberfactoryinventory where size_= ";
    PreparedStatement pst = con.prepareStatement(sql);
    ResultSet rs=pst.executeQuery();
    if(rs.next()){
       String sum=rs.getString("sum(price_total)")+" FCFA";
       totalBySizeTxt.setText(sum);
    }
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
    }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LiberFactory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LiberFactory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LiberFactory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LiberFactory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new LiberFactory().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(LiberFactory.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton deleteBttn;
    private javax.swing.JButton imaged;
    private javax.swing.JLabel imageliber;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField photoname;
    private javax.swing.JTextField priceTxt;
    private javax.swing.JTextField productidTxt;
    private javax.swing.JButton quantitySum;
    private javax.swing.JTextField quantityTxt;
    private javax.swing.JButton refreshBtton;
    private javax.swing.JButton registerProduct;
    private javax.swing.JTextField searchTxt;
    private javax.swing.JTextField sizeJlist;
    private javax.swing.JTextField sortTxt;
    private javax.swing.JTextField sumQTxt;
    private javax.swing.JTextField sumTxt;
    private javax.swing.JButton totalBtton;
    private javax.swing.JButton totalBudget;
    private javax.swing.JTextField totalBySizeTxt;
    private javax.swing.JTextField totalTxt;
    private javax.swing.JButton updateBttn;
    // End of variables declaration//GEN-END:variables
}
