/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import DAO.EseSuenoDao;
import com.toedter.calendar.JDateChooser;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import model.EseSueno;
import model.Product;

/**
 *
 * @author royon
 */
public class LogIn extends javax.swing.JFrame {

    /**
     * Creates new form LogIn
     */
    public LogIn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Username = new javax.swing.JLabel();
        usernameTxt = new javax.swing.JTextField();
        LogIn = new javax.swing.JLabel();
        Username1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        passwordTxt = new javax.swing.JPasswordField();
        choiceTxt = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        comboTxt = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(255, 240, 240));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\royon\\OneDrive\\Images\\Photos\\Ese-Sueno-Logo-Web.png")); // NOI18N

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        Username.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        Username.setForeground(new java.awt.Color(204, 204, 204));
        Username.setText("Username");

        usernameTxt.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        usernameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTxtActionPerformed(evt);
            }
        });

        LogIn.setFont(new java.awt.Font("Arial Black", 0, 48)); // NOI18N
        LogIn.setForeground(new java.awt.Color(255, 0, 0));
        LogIn.setText("LOGIN");

        Username1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        Username1.setForeground(new java.awt.Color(204, 204, 204));
        Username1.setText("Password");

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Emoji", 0, 13)); // NOI18N
        jLabel3.setText("I don't have an account ?");

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Sign Up");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        choiceTxt.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        choiceTxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "x", "Liber Factory", "Liber Gadget" }));

        jButton3.setText("Click Here");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Emoji", 0, 13)); // NOI18N
        jLabel4.setText("You forgot your");

        comboTxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "x", "Username", "Password" }));

        jLabel5.setFont(new java.awt.Font("Segoe UI Emoji", 0, 13)); // NOI18N
        jLabel5.setText("You forgot all your credentials");

        jButton4.setText("Click Here");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(196, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(LogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(121, 121, 121))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(169, 169, 169))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2))
                            .addComponent(choiceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(usernameTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                                .addComponent(Username1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(passwordTxt)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(1, 1, 1)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(comboTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel5))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(LogIn)
                .addGap(77, 77, 77)
                .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(usernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(Username1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(passwordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(choiceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jButton3)
                    .addComponent(comboTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jButton2))
                .addGap(105, 105, 105))
        );

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Copyright © 2023 All Rights Reserved");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 827, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(125, 125, 125)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 749, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(choiceTxt.getSelectedItem().equals("Liber Factory")){
        if(usernameTxt.getText().isEmpty() || passwordTxt.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, " Please Provide All Your Informations");
        }
        else{
            EseSueno sueno = new EseSueno();
            sueno.setUsername(usernameTxt.getText());
            sueno.setPassword_hash(passwordTxt.getText());
            
            EseSuenoDao dao = new EseSuenoDao();
            String feedBack = dao.LogInLiberFactory(sueno);
            
            usernameTxt.setText("");
            passwordTxt.setText("");
            
                            

        }
        }           
        
               
                    
                
            
      

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        SignUp SignUpFrame = new SignUp();
        SignUpFrame.setVisible(true);
        SignUpFrame.pack();
        SignUpFrame.setLocation(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void usernameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTxtActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
  String username = usernameTxt.getText();
  if(comboTxt.getSelectedItem().equals("x") || choiceTxt.getSelectedItem().equals("x") ){
      JOptionPane.showMessageDialog(this, "Choose your case between USERNAME & PASSWORD And also Choose YOUR COMPANY" );
  }
  else if(comboTxt.getSelectedItem().equals("Password")&& choiceTxt.getSelectedItem().equals("Liber Factory")){
      if( ! usernameTxt.getText().trim().isEmpty()){
          JDateChooser dob = new JDateChooser();
              int action = JOptionPane.showConfirmDialog(null, dob,"Enter Password for confirmation",JOptionPane.OK_CANCEL_OPTION);
          try {
              
              Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ese_sueno_db_management","root","");
              String sql = "select * from liberfactory where username=? and birthday_=?";
              PreparedStatement pst = con.prepareStatement(sql);
              pst.setString(1,username);
              SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                String date = sdf.format(dob.getDate());
                pst.setString(2,date);
              ResultSet result = pst.executeQuery();
              EseSueno ese = new EseSueno();
            boolean flag = false;
            while(result.next()){
                ese.setPassword_hash(result.getString("password_hash"));
                
                 JOptionPane.showMessageDialog(rootPane,"Your Password is :" +ese.getPassword_hash());
                
               
                flag=true;
               
                //priceTxt.set
            }
            
            
            if(flag){
                System.out.println("Password : "+ese.getPassword_hash());
                
            }
            con.close();
              if(action < 0){JOptionPane.showMessageDialog(null,"Cancel, X or escape key selected");}
              
                  
            } catch (SQLException ex) {
              Logger.getLogger(LogIn.class.getName()).log(Level.SEVERE, null, ex);
          }
      }else{
          JOptionPane.showMessageDialog(this, "Provide a valid username");
      }
  }else if(comboTxt.getSelectedItem().equals("Username")&& choiceTxt.getSelectedItem().equals("Liber Factory")){
      String pass = passwordTxt.getText();
  
      if( ! passwordTxt.getText().trim().isEmpty()){
          JDateChooser dob = new JDateChooser();
              int action = JOptionPane.showConfirmDialog(null, dob,"Enter Password for confirmation",JOptionPane.OK_CANCEL_OPTION);
          try {
              
              Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ese_sueno_db_management","root","");
              String sql = "select * from liberfactory where password_hash=? and birthday_=?";
              PreparedStatement pst = con.prepareStatement(sql);
              pst.setString(1,pass );
              SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                String date = sdf.format(dob.getDate());
                pst.setString(2,date);
              ResultSet result = pst.executeQuery();
              EseSueno ese = new EseSueno();
            boolean flag = false;
            while(result.next()){
                ese.setUsername(result.getString("username"));
                
                 JOptionPane.showMessageDialog(rootPane,"Your username is : "+ ese.getUsername());
                
               
                flag=true;
               
                
            }
            
            
            if(flag){
                System.out.println("Password : "+ese.getUsername());
                
            }
            con.close();
              if(action < 0){JOptionPane.showMessageDialog(null,"Cancel, X or escape key selected");}
              
                  
            } catch (SQLException ex) {
              Logger.getLogger(LogIn.class.getName()).log(Level.SEVERE, null, ex);
          }
      }else{
          JOptionPane.showMessageDialog(this, "Provide your password");
      }
  }
  else if(comboTxt.getSelectedItem().equals("Password")&& choiceTxt.getSelectedItem().equals("Liber Gadget")){
      if( ! usernameTxt.getText().trim().isEmpty()){
          JDateChooser dob = new JDateChooser();
              int action = JOptionPane.showConfirmDialog(null, dob,"Enter Password for confirmation",JOptionPane.OK_CANCEL_OPTION);
          try {
              
              Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ese_sueno_db_management","root","");
              String sql = "select * from libergadget where username=? and birthday_=?";
              PreparedStatement pst = con.prepareStatement(sql);
              pst.setString(1,username);
              SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                String date = sdf.format(dob.getDate());
                pst.setString(2,date);
              ResultSet result = pst.executeQuery();
              EseSueno ese = new EseSueno();
            boolean flag = false;
            while(result.next()){
                ese.setPassword_hash(result.getString("password_hash"));
                
                 JOptionPane.showMessageDialog(rootPane,"Your Password is :" +ese.getPassword_hash());
                
               
                flag=true;
               
                
            }
            
            
            if(flag){
                System.out.println("Password : "+ese.getPassword_hash());
                
            }
            con.close();
              if(action < 0){JOptionPane.showMessageDialog(null,"Cancel, X or escape key selected");}
              
                  
            } catch (SQLException ex) {
              Logger.getLogger(LogIn.class.getName()).log(Level.SEVERE, null, ex);
          }
      }else{
          JOptionPane.showMessageDialog(this, "Provide a valid username");
      }
  }
  else if(comboTxt.getSelectedItem().equals("Username")&& choiceTxt.getSelectedItem().equals("Liber Gadget")){
      String pass = passwordTxt.getText();
  
      if( ! passwordTxt.getText().trim().isEmpty()){
          JDateChooser dob = new JDateChooser();
              int action = JOptionPane.showConfirmDialog(null, dob,"Enter Password for confirmation",JOptionPane.OK_CANCEL_OPTION);
          try {
              
              Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ese_sueno_db_management","root","");
              String sql = "select * from libergadget where password_hash=? and birthday_=?";
              PreparedStatement pst = con.prepareStatement(sql);
              pst.setString(1,pass );
              SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                String date = sdf.format(dob.getDate());
                pst.setString(2,date);
              ResultSet result = pst.executeQuery();
              EseSueno ese = new EseSueno();
            boolean flag = false;
            while(result.next()){
                ese.setUsername(result.getString("username"));
                
                 JOptionPane.showMessageDialog(rootPane,"Your username is : "+ ese.getUsername());
                
               
                flag=true;
               
                
            }
            
            
            if(flag){
                System.out.println("Password : "+ese.getUsername());
                
            }
            con.close();
              if(action < 0){JOptionPane.showMessageDialog(null,"Cancel, X or escape key selected");}
              
                  
            } catch (SQLException ex) {
              Logger.getLogger(LogIn.class.getName()).log(Level.SEVERE, null, ex);
          }
      }else{
          JOptionPane.showMessageDialog(this, "Provide your password");
      }
  }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         
  if( choiceTxt.getSelectedItem().equals("x") ){
      JOptionPane.showMessageDialog(this, "Choose YOUR COMPANY" );
  }
  else if(choiceTxt.getSelectedItem().equals("Liber Factory")){
      
          JDateChooser dob = new JDateChooser();
              int action = JOptionPane.showConfirmDialog(null, dob,"Enter Date of Birth",JOptionPane.OK_CANCEL_OPTION);
          JTextField phone = new JTextField();
              int action2 = JOptionPane.showConfirmDialog(null, phone,"Enter your phone number",JOptionPane.OK_CANCEL_OPTION);
              String phone_number = phone.getText();
          try {
              
              Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ese_sueno_db_management","root","");
              String sql = "select * from liberfactory where phone_number=? and birthday_=?";
              PreparedStatement pst = con.prepareStatement(sql);
              pst.setString(1,phone_number);
              SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                String date = sdf.format(dob.getDate());
                pst.setString(2,date);
              ResultSet result = pst.executeQuery();
              EseSueno ese = new EseSueno();
            boolean flag = false;
            while(result.next()){
                ese.setUsername(result.getString("username"));
                ese.setPassword_hash(result.getString("password_hash"));
                
                 JOptionPane.showMessageDialog(rootPane,"Your Username is  :" +ese.getUsername() );
                 JOptionPane.showMessageDialog(rootPane, "Your Password is :" +ese.getPassword_hash());
               
                flag=true;
               
                //priceTxt.set
            }
            
            
            if(flag){
                System.out.println("Password : "+ese.getPassword_hash());
                
            }
            con.close();
              if(action < 0){JOptionPane.showMessageDialog(null,"Cancel, X or escape key selected");}
              
                  
            } catch (SQLException ex) {
              Logger.getLogger(LogIn.class.getName()).log(Level.SEVERE, null, ex);
          }
      }else {
          JOptionPane.showMessageDialog(this, "Provide a valid username");
      }
  
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LogIn;
    private javax.swing.JLabel Username;
    private javax.swing.JLabel Username1;
    private javax.swing.JComboBox<String> choiceTxt;
    private javax.swing.JComboBox<String> comboTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField passwordTxt;
    private javax.swing.JTextField usernameTxt;
    // End of variables declaration//GEN-END:variables
}
